name: Smoke Test Every Hour
run-name: Running hourly smoke test

on:
  schedule:
#    - cron: 0 * * * *  # for smoke suite once every hour


jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Setup Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Chrome Browser
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'

      - name: Run Smoke Tests in Chrome
        run: mvn test -D cucumber.filter.tags=@SMOKE -D browser=chrome-headless

      - name: Attach Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Smoke Result HTML report
          path: target/cucumber-report/report.html